# Generated by Django 3.1.7 on 2021-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('openid', models.CharField(max_length=50, verbose_name='openid')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('age', models.CharField(default='', max_length=50, verbose_name='年龄')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='电话')),
                ('bs', models.TextField(verbose_name='既往病史')),
                ('dia', models.TextField(verbose_name='症状信息')),
                ('result', models.TextField(verbose_name='诊断结果')),
                ('yzk', models.TextField(verbose_name='推荐就诊专科')),
                ('photoOD', models.URLField(verbose_name='右眼照片')),
                ('photoOS', models.URLField(verbose_name='左眼照片')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
    ]
