# Generated by Django 3.1.7 on 2021-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetest', '0002_auto_20210817_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='feedback',
            field=models.TextField(default='', verbose_name='意见反馈'),
        ),
    ]
